from django.urls import path, re_path
from people import views

urlpatterns = [
    path('', views.index, name='people.index'),
    re_path(r'^person/(?P<person_id>\d+)/$', views.person, name='person'),
    re_path(r'^person/(?P<person_id>\d+)/edit/$', views.edit_person, name='edit_person'),
    re_path(r'^person/(?P<person_id>\d+)/relatives/$', views.relatives, name='relatives'),
    re_path(r'^person/(?P<person_id>\d+)/relatives/map/$', views.relatives_map, name='relatives_map'),
    re_path(r'^person/(?P<person_id>\d+)/descendants/$', views.descendants, name='descendants'),
    re_path(r'^person/(?P<person_id>\d+)/descendants/map/$', views.descendants_map, name='descendants_map'),
    re_path(r'^person/(?P<person_id>\d+)/descendants/tree/$', views.descendants_tree, name='descendants_tree'),
    re_path(r'^person/(?P<person_id>\d+)/descendants/tree/svg/$', views.descendants_tree_svg, name='descendants_tree_svg'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/$', views.ancestors, name='ancestors'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/report/$', views.ancestors_report, name='report'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/report/undead/$',
            views.ancestors_report_undead,
            name='report_undead'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/report/unburied/$',
            views.ancestors_report_unburied,
            name='report_unburied'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/report/maiden-names/$',
            views.ancestors_report_maiden_names,
            name='report_maiden_names'),
    re_path(r'^report/alive/(?P<year>\d+)/$', views.alive_in_year, name='alive_in_year'),
    re_path(r'^report/alive/(?P<year>\d+)/no-census/$', views.no_census, name='no_census'),
    path('report/maiden-names/', views.unknown_maiden_names, name='maiden_names'),
    path('report/initials/', views.unexpanded_initials, name='initials'),
    path('report/unborn/', views.unborn, name='unborn'),
    path('report/undead/', views.undead, name='undead'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/map/$', views.ancestors_map, name='ancestors_map'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/ringchart/$', views.ring_chart, name='ring_chart'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/ringchart/(?P<depth>\d+)/$', views.ring_chart, name='ring_chart'),
    re_path(r'^person/(?P<person_id>\d+)/ancestors/ringchart/svg/(?P<depth>\d+)/$', views.ring_chart_svg, name='ring_chart_svg'),
    re_path(r'^location/(?P<location_id>\d+)/$', views.location, name='location'),
    re_path(r'^region/(?P<region_name>[\w\W]+)/$', views.region, name='region'),
    re_path(r'^surname/(?P<surname>[\w\W]+)/$', views.surname, name='surname'),
    re_path(r'^forename/(?P<forename>[\w\W]+)/$', views.forename, name='forename'),
    re_path(r'^tag/(?P<slug>[\w-]+)/$', views.tag, name='tag'),
    path('person/add/', views.add_person, name='add_person'),
    path('location/add/', views.add_location, name='add_location'),

    path('public/surnames/', views.surnames, name='surnames'),
]

