# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import people.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', people.fields.UncertainDateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.Person'),
        ),
    ]
