# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20161125_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='marriage',
            options={'ordering': ['husband__surname', 'husband__forename', 'husband__middle_names', 'date']},
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='wedding_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='marriage',
            old_name='wedding_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='marriage',
            name='reference',
            field=models.URLField(blank=True, null=True),
        ),
    ]
