# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20161126_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Birth'), (1, 'Baptism'), (4, 'Death'), (5, 'Burial')]),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband_of', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife_of', to='people.Person'),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
