# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20161126_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'forename', 'middle_names', '-birth__date']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_location',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.Event'),
        ),
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Birth'), (1, 'Baptism'), (3, 'Death'), (4, 'Burial')]),
        ),
    ]
