# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20161126_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='person',
            name='known_as',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
