# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20161205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='forename',
            field=models.CharField(help_text='Forename / given name', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='known_as',
            field=models.CharField(blank=True, help_text='Known as', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(blank=True, help_text='Maiden name', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_names',
            field=models.CharField(blank=True, help_text='Middle names(s)', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(help_text='Surname', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('country', 'county_state_province', 'name')]),
        ),
    ]
