# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import people.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20161219_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='people.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.CASCADE, to='people.Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county_state_province',
            field=models.CharField(help_text='County / state / province', max_length=30, verbose_name='county/state/province'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Place name', max_length=50),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='date',
            field=people.fields.UncertainDateField(blank=True, null=True),
        ),
    ]
