# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20170415_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurnameVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(help_text='Canonical surname', max_length=30)),
                ('variant', models.CharField(help_text='Surname variant', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='photograph',
            options={'ordering': ['-date']},
        ),
    ]
