# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20171120_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Birth/Baptism'), (1, 'Marriage'), (2, 'Death/Burial'), (3, 'Census'), (4, 'Military'), (5, 'Land'), (6, 'Press')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
